apiVersion: v1
kind: Service
metadata:
  name: my-app-service-node
spec:
  selector:
    app: my-app
  ports:
  - name: nginx-service
    port: 9001
    targetPort: 80
    nodePort: 32001
  - name: multitool-service
    port: 9002
    targetPort: 1180
    nodePort: 32002
  type: NodePort
