apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - name: nginx-service
    port: 9001
    targetPort: 80
  - name: multitool-service
    port: 9002
    targetPort: 1180
