apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-cm
data:
  http_port: "8080"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html>
     <head>
       <title>Hello from k8s!!!</title>
     </head>
     <body>
       <h1>It's work!!!</h1>
     </body>
    </html>
